# Generated by Django 4.2.6 on 2023-10-18 20:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agendamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('horaDaVacinacao', models.TimeField()),
                ('dataDaVacinacao', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='CrescimentoCrianca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('altura', models.FloatField()),
                ('peso', models.FloatField()),
                ('perimetro', models.FloatField()),
                ('idadeCrianca', models.IntegerField()),
                ('imc', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Crianca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomeDaCrianca', models.CharField(max_length=150)),
                ('cpf', models.CharField(max_length=14)),
                ('dataDeNascimento', models.DateField()),
                ('nomeDaMae', models.CharField(max_length=150)),
                ('cpfDaMae', models.CharField(max_length=14)),
                ('dataNascimentoMae', models.DateField()),
                ('unidadeSaudeFamiliar', models.CharField(max_length=150)),
                ('maternidade', models.CharField(max_length=150)),
                ('tipoDoParto', models.CharField(max_length=150)),
                ('idadeGestacional', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Cuidador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
                ('grauDeParentesco', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=150)),
                ('telefone', models.CharField(max_length=11, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Endereco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logradouro', models.CharField(max_length=100)),
                ('cep', models.CharField(max_length=9)),
                ('numero', models.CharField(max_length=100)),
                ('estado', models.CharField(max_length=50)),
                ('municipio', models.CharField(max_length=20)),
                ('complemento', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Medico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NomeDoMedico', models.CharField(max_length=100)),
                ('Conselho', models.CharField(max_length=100)),
                ('Escilidade', models.CharField(max_length=100)),
                ('NumeroDeInscricao', models.CharField(max_length=100)),
                ('Email', models.CharField(max_length=100)),
                ('Telefone', models.CharField(max_length=11)),
            ],
        ),
        migrations.CreateModel(
            name='ProfissionalDeSaude',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
                ('cpf', models.CharField(max_length=14, unique=True)),
                ('email', models.CharField(max_length=150)),
                ('senha', models.CharField(max_length=150)),
                ('telefone', models.CharField(max_length=11, unique=True)),
                ('tipoProfissional', models.CharField(max_length=150)),
                ('conselho', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Vacina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipoVacina', models.CharField(max_length=150)),
                ('dataVacina', models.DateField()),
                ('lote', models.CharField(max_length=150)),
                ('fabricante', models.CharField(max_length=150)),
                ('dataFabricacao', models.DateField()),
                ('status', models.CharField(choices=[('atrasado', 'Atrasado'), ('agendado', 'Agendado')], default='agendado', max_length=10)),
                ('idAgendamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userapp.agendamento')),
                ('profissional', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vacinas', to='userapp.profissionaldesaude')),
            ],
        ),
        migrations.CreateModel(
            name='UnidadeSaudeFamiliar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criadoEmDiaMesAno', models.DateField()),
                ('idCrianca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userapp.crianca')),
                ('idCuidador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userapp.cuidador')),
                ('idEndereco', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userapp.endereco')),
                ('idProfissionalDeSaude', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userapp.profissionaldesaude')),
            ],
        ),
        migrations.CreateModel(
            name='ProfissionalSaudeEUSF',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criadoEmDiaMesAno', models.DateField()),
                ('idProfissionalDeSaude', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userapp.profissionaldesaude')),
                ('idUSF', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userapp.unidadesaudefamiliar')),
            ],
        ),
        migrations.CreateModel(
            name='HistoricoDeVacinas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criadoEmDiaMesAno', models.DateField()),
                ('idAgendamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userapp.agendamento')),
                ('idVacina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userapp.vacina')),
            ],
        ),
        migrations.CreateModel(
            name='CuidadorCrianca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criadoEmDiaMesAno', models.DateField()),
                ('idCrianca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userapp.crianca')),
                ('idCuidador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userapp.cuidador')),
            ],
        ),
        migrations.CreateModel(
            name='CriancaVacina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criadoEmDiaMesAno', models.DateField()),
                ('idCrianca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userapp.crianca')),
                ('idVacina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userapp.vacina')),
            ],
        ),
        migrations.CreateModel(
            name='Consulta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dataConsulta', models.DateField()),
                ('tipoDaConsulta', models.CharField(choices=[('particular', 'Particular'), ('sus', 'SUS')], default='sus', max_length=10)),
                ('idEndereco', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userapp.endereco')),
                ('idMedico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userapp.medico')),
            ],
        ),
    ]
