# Generated by Django 4.2.6 on 2023-10-22 04:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CuidadosEspeciais',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ferro', models.CharField(choices=[('sim', 'Sim'), ('não', 'Não')], default='nao visualizado', max_length=10)),
                ('micronutrientes', models.CharField(choices=[('sim', 'Sim'), ('não', 'Não')], default='nao visualizado', max_length=10)),
                ('vitaminaA', models.CharField(choices=[('sim', 'Sim'), ('não', 'Não')], default='nao visualizado', max_length=10)),
                ('odonto', models.CharField(choices=[('sim', 'Sim'), ('não', 'Não')], default='nao visualizado', max_length=10)),
                ('acidentesDomesticos', models.CharField(choices=[('sim', 'Sim'), ('não', 'Não')], default='nao visualizado', max_length=10)),
                ('negligencias', models.CharField(choices=[('sim', 'Sim'), ('não', 'Não')], default='nao visualizado', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='SinaisAlerta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diarreia', models.CharField(choices=[('sim', 'Sim'), ('não', 'Não')], default='nao visualizado', max_length=10)),
                ('vomitos', models.CharField(choices=[('sim', 'Sim'), ('não', 'Não')], default='nao visualizado', max_length=10)),
                ('dificuldadeRespirar', models.CharField(choices=[('sim', 'Sim'), ('não', 'Não')], default='nao visualizado', max_length=10)),
                ('febre', models.CharField(choices=[('sim', 'Sim'), ('não', 'Não')], default='nao visualizado', max_length=10)),
                ('hipotermia', models.CharField(choices=[('sim', 'Sim'), ('não', 'Não')], default='nao visualizado', max_length=10)),
                ('sibilancias', models.CharField(choices=[('sim', 'Sim'), ('não', 'Não')], default='nao visualizado', max_length=10)),
                ('convulcoes', models.CharField(choices=[('sim', 'Sim'), ('não', 'Não')], default='nao visualizado', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Desenvolvimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brincaEsconde', models.CharField(choices=[('presente', 'Presente'), ('ausente', 'Ausente'), ('nao visualizado', 'Não visualizado')], default='nao visualizado', max_length=15)),
                ('objetosMao', models.CharField(choices=[('presente', 'Presente'), ('ausente', 'Ausente'), ('nao visualizado', 'Não visualizado')], default='nao visualizado', max_length=15)),
                ('duplicaSilaba', models.CharField(choices=[('presente', 'Presente'), ('ausente', 'Ausente'), ('nao visualizado', 'Não visualizado')], default='nao visualizado', max_length=15)),
                ('senta', models.CharField(choices=[('presente', 'Presente'), ('ausente', 'Ausente'), ('nao visualizado', 'Não visualizado')], default='nao visualizado', max_length=15)),
                ('idCrescimentoCrianca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userapp.crescimentocrianca')),
            ],
        ),
    ]
