# Generated by Django 4.2.6 on 2023-10-28 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0002_cuidadosespeciais_sinaisalerta_desenvolvimento'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aleitamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aleitamento', models.CharField(choices=[('leite materno exclusivo', 'Leite materno exclusivo'), ('leite artificials', 'Leite artificial'), ('leite materno complementado', 'Leite materno complementado')], default='Escolha', max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='LeiteArtificial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parouAmamentar', models.CharField(choices=[('sim', 'Sim'), ('não', 'Não')], default='nao visualizado', max_length=10)),
                ('idadeParou', models.IntegerField()),
                ('alimentoCrianca', models.CharField(max_length=150)),
                ('porcoesFrutasDia', models.CharField(max_length=150)),
                ('alimentosIndustrializado', models.CharField(choices=[('sim', 'Sim'), ('não', 'Não')], default='nao visualizado', max_length=10)),
                ('qualAlimentoIndust', models.CharField(max_length=150)),
            ],
        ),
        migrations.AlterField(
            model_name='crescimentocrianca',
            name='idadeCrianca',
            field=models.CharField(choices=[('primeira semana', 'Primeira semana'), ('1 mês', '1 mês'), ('2 meses', '2 meses'), ('3 meses', '3 meses'), ('4 meses', '4 meses'), ('5 meses', '5 meses'), ('6 meses', '6 meses'), ('9 meses', '9 meses'), ('12 meses', '12 meses'), ('18 meses', '18 meses'), ('24 meses', '24 meses'), ('36 meses', '36 meses')], default='Escolha', max_length=15),
        ),
    ]
