# Generated by Django 4.2.6 on 2023-10-30 18:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0003_aleitamento_leiteartificial_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vacina',
            name='idAgendamento',
        ),
        migrations.RemoveField(
            model_name='vacina',
            name='profissional',
        ),
        migrations.RemoveField(
            model_name='vacina',
            name='status',
        ),
        migrations.AlterField(
            model_name='leiteartificial',
            name='idadeParou',
            field=models.CharField(max_length=150),
        ),
        migrations.CreateModel(
            name='Aplicacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('atrasado', 'Atrasado'), ('agendado', 'Agendado')], default='agendado', max_length=10)),
                ('idAgendamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userapp.agendamento')),
                ('idVacina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userapp.vacina')),
                ('profissional', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vacinas', to='userapp.profissionaldesaude')),
            ],
        ),
    ]
