# Generated by Django 4.2.6 on 2023-10-30 18:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0004_remove_vacina_idagendamento_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vacina',
            name='dataVacina',
        ),
    ]
