# Generated by Django 4.2.7 on 2023-11-30 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0006_exameocular'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cuidadosespeciais',
            name='acidentesDomesticos',
        ),
        migrations.RemoveField(
            model_name='cuidadosespeciais',
            name='ferro',
        ),
        migrations.RemoveField(
            model_name='cuidadosespeciais',
            name='micronutrientes',
        ),
        migrations.RemoveField(
            model_name='cuidadosespeciais',
            name='negligencias',
        ),
        migrations.RemoveField(
            model_name='cuidadosespeciais',
            name='odonto',
        ),
        migrations.RemoveField(
            model_name='cuidadosespeciais',
            name='vitaminaA',
        ),
        migrations.AddField(
            model_name='cuidadosespeciais',
            name='acidentes_domiciliares',
            field=models.CharField(choices=[('NAO', 'NAO'), ('SIM', 'SIM')], default='NAO', max_length=50),
        ),
        migrations.AddField(
            model_name='cuidadosespeciais',
            name='funcionamento_intestino_colicas',
            field=models.CharField(choices=[('PRESERVADO', 'PRESERVADO'), ('NAO_PRESERVADO', 'NAO PRESERVADO')], default='PRESERVADO', max_length=50),
        ),
        migrations.AddField(
            model_name='cuidadosespeciais',
            name='higiene_cuidados_gerais',
            field=models.CharField(choices=[('PRESERVADO', 'PRESERVADO'), ('NAO_PRESERVADO', 'NAO PRESERVADO')], default='PRESERVADO', max_length=50),
        ),
        migrations.AddField(
            model_name='cuidadosespeciais',
            name='posicao_sono_berco',
            field=models.CharField(choices=[('NAO', 'NAO'), ('SIM', 'SIM')], default='NAO', max_length=50),
        ),
        migrations.AddField(
            model_name='cuidadosespeciais',
            name='sinais_violencias_negligencias',
            field=models.CharField(choices=[('PRESENTE', 'PRESENTE'), ('AUSENTE', 'AUSENTE')], default='AUSENTE', max_length=50),
        ),
        migrations.AddField(
            model_name='cuidadosespeciais',
            name='tempo_sono_24_horas',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
