# Generated by Django 4.2.5 on 2023-12-04 02:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0007_remove_cuidadosespeciais_acidentesdomesticos_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DesenvolvimentoInfantil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reflexo_moro', models.CharField(blank=True, choices=[('P', 'Presente'), ('A', 'Ausente'), ('NV', 'Não Verificado')], max_length=2)),
                ('reflexo_cocleo_palpebral', models.CharField(blank=True, choices=[('P', 'Presente'), ('A', 'Ausente'), ('NV', 'Não Verificado')], max_length=2)),
                ('reflexo_succao', models.CharField(blank=True, choices=[('P', 'Presente'), ('A', 'Ausente'), ('NV', 'Não Verificado')], max_length=2)),
                ('bracos_pernas_flexionados', models.CharField(blank=True, choices=[('P', 'Presente'), ('A', 'Ausente'), ('NV', 'Não Verificado')], max_length=2)),
                ('postura_cabeca_lateralizada', models.CharField(blank=True, choices=[('P', 'Presente'), ('A', 'Ausente'), ('NV', 'Não Verificado')], max_length=2)),
                ('observa_rosto', models.CharField(blank=True, choices=[('P', 'Presente'), ('A', 'Ausente'), ('NV', 'Não Verificado')], max_length=2)),
                ('reage_som', models.CharField(blank=True, choices=[('P', 'Presente'), ('A', 'Ausente'), ('NV', 'Não Verificado')], max_length=2)),
                ('eleva_cabeca', models.CharField(blank=True, choices=[('P', 'Presente'), ('A', 'Ausente'), ('NV', 'Não Verificado')], max_length=2)),
                ('crianca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userapp.crianca')),
            ],
        ),
    ]
