# Generated by Django 4.2.7 on 2023-12-09 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0010_remove_crescimentocrianca_idadecrianca_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='crescimentocrianca',
            name='idade',
        ),
        migrations.RemoveField(
            model_name='crescimentocrianca',
            name='idade_crianca',
        ),
        migrations.RemoveField(
            model_name='crescimentocrianca',
            name='perimetro_cefalico',
        ),
        migrations.AddField(
            model_name='crescimentocrianca',
            name='idadeCrianca',
            field=models.CharField(choices=[('primeira semana', 'Primeira semana'), ('1 mês', '1 mês'), ('2 meses', '2 meses'), ('3 meses', '3 meses'), ('4 meses', '4 meses'), ('5 meses', '5 meses'), ('6 meses', '6 meses'), ('9 meses', '9 meses'), ('12 meses', '12 meses'), ('18 meses', '18 meses'), ('24 meses', '24 meses'), ('36 meses', '36 meses')], default='Escolha', max_length=15),
        ),
    ]
