# Generated by Django 4.2.7 on 2023-12-14 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0011_remove_crescimentocrianca_idade_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='crescimentocrianca',
            name='genero',
            field=models.CharField(choices=[('M', 'Menino'), ('F', 'Menina')], default='M', max_length=1),
        ),
    ]
